name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file server/Dockerfile --tag hikari03/hikup:edge

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push hikari03/hikup:edge

